.local-command-test-git:
  extends: .template-tiki-manager-commands-git
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP
      - $SCHEDULER == "update_vendor"

.local-command-test-svn:
  extends: .template-tiki-manager-commands-svn
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP
      - $SCHEDULER == "update_vendor"

.local-command-test-src:
  extends: .template-tiki-manager-commands-src
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP
      - $SCHEDULER == "update_vendor"

local-create-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: CreateInstanceCommandTest.php

local-create-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: CreateInstanceCommandTest.php

local-create-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: CreateInstanceCommandTest.php

local-update-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: UpdateInstanceCommandTest.php

local-update-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: UpdateInstanceCommandTest.php

local-update-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: UpdateInstanceCommandTest.php

local-upgrade-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: UpgradeInstanceCommandTest.php

local-upgrade-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: UpgradeInstanceCommandTest.php

local-upgrade-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: UpgradeInstanceCommandTest.php

local-backup-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: BackupInstanceCommandTest.php

local-backup-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: BackupInstanceCommandTest.php

local-backup-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: BackupInstanceCommandTest.php

local-restore-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: RestoreInstanceCommandTest.php

local-restore-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: RestoreInstanceCommandTest.php

local-restore-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: RestoreInstanceCommandTest.php

local-clone-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: CloneInstanceCommandTest.php

local-clone-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: CloneInstanceCommandTest.php

local-clone-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: CloneInstanceCommandTest.php

local-clone-upgrade-instance-git:
  extends: .local-command-test-git
  variables:
    VCS: git
    TEST_FILE: CloneAndUpgradeCommandTest.php

local-clone-upgrade-instance-svn:
  extends: .local-command-test-svn
  variables:
    VCS: svn
    TEST_FILE: CloneAndUpgradeCommandTest.php

local-clone-upgrade-instance-src:
  extends: .local-command-test-src
  variables:
    VCS: src
    TEST_FILE: CloneAndUpgradeCommandTest.php
