.local-command-test-git: &local-command-test-git
  extends: .template-tiki-manager-commands-git
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP
      - $SCHEDULER == "update_vendor"

local-create-instance-git-php74: 
  <<: *local-command-test-git
  variables:
    TEST_FILE: CreateInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-create-instance-git-php81: 
  <<: *local-command-test-git
  variables:
    TEST_FILE: CreateInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-update-instance-git-php74: 
  <<: *local-command-test-git
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-update-instance-git-php81: 
  <<: *local-command-test-git
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-upgrade-instance-git-php74:
  <<: *local-command-test-git
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-upgrade-instance-git-php81:
  <<: *local-command-test-git
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-backup-instance-git-php74:
  <<: *local-command-test-git
  variables:
    TEST_FILE: BackupInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-backup-instance-git-php81:
  <<: *local-command-test-git
  variables:
    TEST_FILE: BackupInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-restore-instance-git-php74:
  <<: *local-command-test-git
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-restore-instance-git-php81:
  <<: *local-command-test-git
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-clone-instance-git-php74:
  <<: *local-command-test-git
  variables:
    TEST_FILE: CloneInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-clone-instance-git-php81:
  <<: *local-command-test-git
  variables:
    TEST_FILE: CloneInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-clone-upgrade-instance-git-php74:
  <<: *local-command-test-git
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php
    PHP_VERSION: "7.4"

local-clone-upgrade-instance-git-php81:
  <<: *local-command-test-git
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php
    PHP_VERSION: "8.1"