.local-command-test-src: &local-command-test-src
  extends: .template-tiki-manager-commands-src
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP

local-create-instance-src-php74: 
  <<: *local-command-test-src
  variables:
    TEST_FILE: CreateInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-create-instance-src-php81: 
  <<: *local-command-test-src
  variables:
    TEST_FILE: CreateInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-update-instance-src-php74: 
  <<: *local-command-test-src
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-update-instance-src-php81: 
  <<: *local-command-test-src
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-upgrade-instance-src-php74:
  <<: *local-command-test-src
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-upgrade-instance-src-php81:
  <<: *local-command-test-src
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-backup-instance-src-php74:
  <<: *local-command-test-src
  variables:
    TEST_FILE: BackupInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-backup-instance-src-php81:
  <<: *local-command-test-src
  variables:
    TEST_FILE: BackupInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-restore-instance-src-php74:
  <<: *local-command-test-src
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-restore-instance-src-php81:
  <<: *local-command-test-src
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-clone-instance-src-php74:
  <<: *local-command-test-src
  variables:
    TEST_FILE: CloneInstanceCommandTest.php
    PHP_VERSION: "7.4"

local-clone-instance-src-php81:
  <<: *local-command-test-src
  variables:
    TEST_FILE: CloneInstanceCommandTest.php
    PHP_VERSION: "8.1"

local-clone-upgrade-instance-src-php74:
  <<: *local-command-test-src
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php
    PHP_VERSION: "7.4"

local-clone-upgrade-instance-src-php81:
  <<: *local-command-test-src
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php
    PHP_VERSION: "8.1"