.ssh-command-test-git:
  image: tikiwiki/tikimanager-ci:7.4-qa-ssh
  extends: .template-tiki-manager-commands-git
  services:
    - name: mysql:5.6
      alias: mysql
  variables:
    VCS: git
  before_script:
    - echo APP_ENV=gitlab-ci >> .env
    - echo DEFAULT_VCS=$VCS >> .env
    - echo TEST_INSTANCE_TYPE=ssh >> .env
    - cat .env
    - ssh-keygen -t rsa -f ./data/id_rsa -q -P ""
    - "[ -d ~/.ssh ] || mkdir ~/.ssh"
    - service ssh start
    - source .env.gitlab-ci
    - sshpass -p $SSH_HOST_PASS ssh-copy-id -o "StrictHostKeyChecking=no" -i ./data/id_rsa $SSH_HOST_USER@$SSH_HOST_NAME
    - composer install $COMPOSER_FLAGS
    - composer bin all install $COMPOSER_FLAGS
  only:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH

ssh-create-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: CreateInstanceCommandTest.php

ssh-update-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php

ssh-upgrade-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php

ssh-backup-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: BackupInstanceCommandTest.php

ssh-restore-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php

ssh-clone-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: CloneInstanceCommandTest.php

ssh-clone-upgrade-instance-git:
  extends: .ssh-command-test-git
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php
