.local-command-test-git: &local-command-test-git
  extends: .template-tiki-manager-commands-git
  except:
    variables:
      - $INSTANCE_TYPE == $INSTANCE_TYPE_SSH
      - $INSTANCE_TYPE == $INSTANCE_TYPE_FTP
      - $SCHEDULER == "update_vendor"
      
.functional-parallel-matrix: &functional-parallel-matrix
  parallel:
    matrix:
      - PHP_VERSION: ['7.4', '8.4']      

local-create-instance-git: 
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: CreateInstanceCommandTest.php

local-update-instance-git: 
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: UpdateInstanceCommandTest.php

local-upgrade-instance-git:
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: UpgradeInstanceCommandTest.php

local-backup-instance-git:
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: BackupInstanceCommandTest.php

local-restore-instance-git:
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: RestoreInstanceCommandTest.php

local-clone-instance-git:
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: CloneInstanceCommandTest.php

local-clone-upgrade-instance-git:
  <<: *local-command-test-git
  <<: *functional-parallel-matrix
  variables:
    TEST_FILE: CloneAndUpgradeCommandTest.php